"""LangGraph state definition for the CI Agent."""
from __future__ import annotations

from typing import Annotated, Any
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class CIAgentState(TypedDict):
    """Full state that flows through every node in the CI agent graph."""

    # ── LangGraph message history (append-only via add_messages) ──────────
    messages: Annotated[list, add_messages]

    # ── Task classification (set by supervisor) ────────────────────────────
    task_type: str
    """One of: daily_brief | alert_scan | competitor_query | pricing_query |
    review_query | news_query | strategy | ingest | unknown"""

    task_input: str
    """Raw user request string."""

    # ── Data collected from intel DB ───────────────────────────────────────
    collected_data: dict[str, Any]
    """Keyed by entity: reviews, news, competitors, pricing, intel, summary"""

    # ── Analysis results ───────────────────────────────────────────────────
    analysis: dict[str, Any]
    """Sentiment trends, anomalies, top keywords, competitor moves, etc."""

    # ── Alert engine output ────────────────────────────────────────────────
    alerts: list[dict[str, Any]]
    """Unacknowledged + newly detected alerts."""

    # ── Executive outputs ──────────────────────────────────────────────────
    briefing: str
    """Markdown executive briefing generated by briefing_generator node."""

    recommendations: list[str]
    """Prioritised strategic recommendations from strategist node."""

    # ── Observability ──────────────────────────────────────────────────────
    metadata: dict[str, Any]
    """Token usage, cache hits, elapsed time, node trace, etc."""
